name: Cross-platform Build and Test

on:
  push:
    branches:
      - '**develop**'
      - '**master**'
  pull_request:
    branches:
      - '**develop**'
      - '**master**'

jobs:
  cross_build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Ensure bash available (Windows only)
        if: runner.os == 'Windows'
        run: |
          choco install git -y
          echo "Bash installed for Windows runner"

      - name: Make scripts executable
        shell: bash
        run: |
          chmod +x ci.sh || true
          chmod +x build.sh || true

      - name: Run CI build
        shell: bash
        run: |
          echo "Running CI script on $RUNNER_OS"
          ./ci.sh

      - name: Deploy
        if: success()
        shell: bash
        run: |
          echo "Deploy step (customize as needed)"
