name: Cross-platform Build and Test

on:
  push:
    branches:
      - '**develop**'
      - '**master**'
  pull_request:
    branches:
      - '**develop**'
      - '**master**'

jobs:
  cross_build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Set up Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Build and Test (Cross-Platform)
        shell: bash
        run: |
          set -e
          echo "=== Cleaning previous build ==="
          rm -rf build

          echo "=== Creating build directory ==="
          mkdir -p build
          cd build

          echo "=== Configuring project with CMake + Ninja ==="
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release ..

          echo "=== Building project ==="
          cmake --build . --config Release

          echo "=== Running tests ==="
          ctest --output-on-failure

          echo "=== Build and test complete ==="

      - name: Deploy
        if: success()
        shell: bash
        run: echo "Deploy step (customize as needed)"
